services:
  db:
    image: postgres:15
    container_name: shopbot_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - botnet

  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: shopbot_app
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - botnet
    command: python bot/main.py
    volumes:
      - ../:/app

  admin:
    build:
      context: ..
      dockerfile: docker/Dockerfile-django
    container_name: django_admin
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - botnet
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    command: python admin_panel/manage.py runserver 0.0.0.0:8000

networks:
  botnet:

volumes:
  postgres_data:
