services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ./.env     # اشاره به فایل .env در همین پوشه
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - botnet

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: python bot/main.py
    env_file:
      - ./.env     # اگر ربات هم به متغیرهای .env نیاز دارد
    volumes:
      - ../:/app
    networks:
      - botnet

networks:
  botnet:

volumes:
  postgres_data:
