version: "3.8"

services:
  db:
    image: postgres:15
    container_name: shopbot_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - botnet

  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: shopbot_app
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - botnet
    command: python bot/main.py

networks:
  botnet:

volumes:
  postgres_data:
